import Image from "next/image";
import Link from "next/link";
import type { NextPage } from "next";
import { MetaHeader } from "~~/components/MetaHeader";

/** Homepage explains how the game works and offers enter contest button
 */

const Home: NextPage = () => {
  return (
    <>
      <MetaHeader />
      <div className="bg-base-300 grow px-5 md:px-10 xl:px-20">
        <h1 className="font-cubano text-4xl md:text-6xl xl:text-7xl text-center my-14 lg:my-24"> Vaults of Fortune</h1>

        <div className="grid grid-cols-1 xl:grid-cols-8 gap-14 items-center justify-center my-14">
          <div className="col-span-8 xl:col-span-3 flex justify-center">
            <Image src="/vault.png" width="500" height="500" alt="cartoon vault" />
          </div>

          <div className=" col-span-8 xl:col-span-5">
            <h2 className="font-cubano text-4xl mb-5 text-center">How to Play</h2>
            <div className="bg-base-200 rounded-xl py-10 pl-10 lg:pl-20 pr-5 lg:pr-10">
              <ol className="text-2xl list-decimal list-outside">
                <li className="mb-5">Enter a contest to be airdropped 10,000 GLD tokens</li>
                <li className="mb-5">
                  Compete for the highest return on investment over 3 rounds that last a maximum of 5 minutes each
                </li>
                <li className="mb-5">During each round, allocate your GLD tokens to each vault as you see fit</li>
                <li className="mb-5">
                  After allocating 100% of your GLD tokens into the vaults, put pressure on competition by clicking the{" "}
                  {`"ready"`} button to expadite the round closing process
                </li>
                <li className="mb-5">
                  At the end of each round, the market contract sends or takes GLD tokens from the vaults based on the
                  random numbers generated by VRF
                </li>
                <li className="mb-0">Highest net worth at the end of round 3 is the winner</li>
              </ol>
            </div>
            <div className="flex justify-center mt-5">
              <Link className="btn btn-accent btn-lg capitalize px-10" href="/contest">
                Go to Contest
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
