import { useState } from "react";
import type { NextPage } from "next";
import { MetaHeader } from "~~/components/MetaHeader";
import { Leaderboard, Portfolio, Round, Vaults } from "~~/components/vaults-of-fortune/";
import { useScaffoldEventSubscriber } from "~~/hooks/scaffold-eth";

/** Homepage renders all of the child components and manages round start/end modals
 *
 * when round starts, modal pops up to let users know
 * when round ends, modal pops up showing the ROI results generated by VRF
 */

const Home: NextPage = () => {
  const [showRoundStartModal, setShowRoundStartModal] = useState(false);
  const [isRoundEnd, setIsRoundEnd] = useState(false);
  const [roundNumber, setRoundNumber] = useState(0);
  const [roundResults, setRoundResults] = useState({
    contestNumber: 0,
    roundNumber: 0,
    lowRiskVaultROI: 0,
    mediumRiskVaultROI: 0,
    highRiskVaultROI: 0,
  });

  useScaffoldEventSubscriber({
    contractName: "Market",
    eventName: "RoundOpen",
    listener: logs => {
      logs.map(log => {
        const { roundNumber } = log.args;
        setShowRoundStartModal(true);
        setRoundNumber(Number(roundNumber));
      });
    },
  });

  useScaffoldEventSubscriber({
    contractName: "Market",
    eventName: "RoundResults",
    listener: logs => {
      logs.map(log => {
        const { contestNumber, roundNumber, lowRiskVaultROI, mediumRiskVaultROI, highRiskVaultROI } = log.args;
        setRoundResults(() => {
          return {
            contestNumber: Number(contestNumber),
            roundNumber: Number(roundNumber),
            lowRiskVaultROI: Number(lowRiskVaultROI),
            mediumRiskVaultROI: Number(mediumRiskVaultROI),
            highRiskVaultROI: Number(highRiskVaultROI),
          };
        });
      });
      setIsRoundEnd(true);
    },
  });

  return (
    <>
      <MetaHeader />

      <div className="bg-base-300 py-14 min-h-[468px] px-5 xl:px-10">
        {/* <h1 className="text-6xl text-center font-cubano my-10">Vaults Of Fortune</h1> */}
        <div className="rounded-xl grid grid-cols-1 2xl:grid-cols-3 gap-14">
          <div>
            <Leaderboard />
          </div>
          <div>
            <Portfolio />
          </div>
          <div>
            <Round />
          </div>
        </div>
      </div>
      <div className="p-5 xl:p-10">
        <div className="grid grid-cols-1 2xl:grid-cols-3 gap-14">
          <Vaults />
        </div>
      </div>

      {showRoundStartModal && (
        <div className="modal modal-open">
          <div className="modal-box">
            <h3 className="font-cubano text-3xl text-center mb-5">Round {roundNumber} Started!</h3>
            <p className="text-center text-xl">Allocate your funds before the clock runs out!</p>
            <div className="modal-action">
              <button className="btn" onClick={() => setShowRoundStartModal(false)}>
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {isRoundEnd && (
        <div className="modal modal-open">
          <div className="modal-box">
            <h3 className="font-cubano text-3xl text-center mb-5">End of Round {roundResults.roundNumber}</h3>
            <p className="text-center text-xl">The Low Risk Vault returned {roundResults.lowRiskVaultROI}%</p>
            <p className="text-center text-xl">The Medium Risk Vault returned {roundResults.mediumRiskVaultROI}%</p>
            <p className="text-center text-xl">The High Risk Vault returned {roundResults.highRiskVaultROI}%</p>

            <div className="modal-action">
              <button className="btn" onClick={() => setIsRoundEnd(false)}>
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default Home;
