import Image from "next/image";
import { useRouter } from "next/router";
import type { NextPage } from "next";
import { MetaHeader } from "~~/components/MetaHeader";
import { useScaffoldContractWrite } from "~~/hooks/scaffold-eth";

/** Homepage explains how the game works and offers enter contest button
 */

const Home: NextPage = () => {
  const {
    writeAsync: enterContest,
    // isLoading,
    // isMining,
  } = useScaffoldContractWrite({
    contractName: "Market",
    functionName: "enterContest",
  });

  const router = useRouter();

  const handleEnterContest = async () => {
    await enterContest();
    // Redirect to another page after the logic of enterContest
    router.push("/game");
  };

  return (
    <>
      <MetaHeader />
      <div className="bg-base-300 grow px-5 md:px-10 xl:px-20">
        <h1 className="font-cubano text-4xl lg:text-5xl text-center my-14"> Vaults of Fortune</h1>

        <div className="grid grid-cols-1 xl:grid-cols-2 items-center gap-10">
          <div className="rounded-2xl overflow-hidden flex justify-center">
            <Image src="/vault.png" width="500" height="500" alt="cartoon vault" />
          </div>

          <div>
            <ol className="text-2xl list-decimal list-inside md:list-outside">
              <li className="mb-5">Enter a contest to be airdropped 10,000 GLD tokens</li>
              <li className="mb-5">Compete for the highest return on investment over 3 rounds</li>
              <li className="mb-5">During each round, allocate your GLD tokens to each vault as you see fit</li>
              <li className="mb-5">
                After allocating 100% of your GLD tokens into the vaults, put pressure on competition by clicking the{" "}
                {`"ready"`} button to trigger the round closing process
              </li>
              <li className="mb-5">
                At the end of each round, the market contract sends or takes GLD tokens from the vaults based on the
                random numbers generated by VRF
              </li>
              <li className="mb-5">Highest net worth at the end of the 3rd round is the winner</li>
            </ol>
          </div>
        </div>

        <div className="text-center my-14">
          <button className="w-48 capitalize text-xl btn btn-accent" onClick={handleEnterContest}>
            Enter Contest
          </button>
        </div>
      </div>
    </>
  );
};

export default Home;
